// This file was generated by counterfeiter
package fake_container_configurer

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-linux/containerizer"
)

type FakeContainerConfigurer struct {
	BindMountRootfsStub        func(rootFSPath string) error
	bindMountRootfsMutex       sync.RWMutex
	bindMountRootfsArgsForCall []struct {
		rootFSPath string
	}
	bindMountRootfsReturns struct {
		result1 error
	}
	PivotRootStub        func(rootFSPath string) error
	pivotRootMutex       sync.RWMutex
	pivotRootArgsForCall []struct {
		rootFSPath string
	}
	pivotRootReturns struct {
		result1 error
	}
	ChangeUserStub        func(uid, gid int) error
	changeUserMutex       sync.RWMutex
	changeUserArgsForCall []struct {
		uid int
		gid int
	}
	changeUserReturns struct {
		result1 error
	}
}

func (fake *FakeContainerConfigurer) BindMountRootfs(rootFSPath string) error {
	fake.bindMountRootfsMutex.Lock()
	fake.bindMountRootfsArgsForCall = append(fake.bindMountRootfsArgsForCall, struct {
		rootFSPath string
	}{rootFSPath})
	fake.bindMountRootfsMutex.Unlock()
	if fake.BindMountRootfsStub != nil {
		return fake.BindMountRootfsStub(rootFSPath)
	} else {
		return fake.bindMountRootfsReturns.result1
	}
}

func (fake *FakeContainerConfigurer) BindMountRootfsCallCount() int {
	fake.bindMountRootfsMutex.RLock()
	defer fake.bindMountRootfsMutex.RUnlock()
	return len(fake.bindMountRootfsArgsForCall)
}

func (fake *FakeContainerConfigurer) BindMountRootfsArgsForCall(i int) string {
	fake.bindMountRootfsMutex.RLock()
	defer fake.bindMountRootfsMutex.RUnlock()
	return fake.bindMountRootfsArgsForCall[i].rootFSPath
}

func (fake *FakeContainerConfigurer) BindMountRootfsReturns(result1 error) {
	fake.BindMountRootfsStub = nil
	fake.bindMountRootfsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeContainerConfigurer) PivotRoot(rootFSPath string) error {
	fake.pivotRootMutex.Lock()
	fake.pivotRootArgsForCall = append(fake.pivotRootArgsForCall, struct {
		rootFSPath string
	}{rootFSPath})
	fake.pivotRootMutex.Unlock()
	if fake.PivotRootStub != nil {
		return fake.PivotRootStub(rootFSPath)
	} else {
		return fake.pivotRootReturns.result1
	}
}

func (fake *FakeContainerConfigurer) PivotRootCallCount() int {
	fake.pivotRootMutex.RLock()
	defer fake.pivotRootMutex.RUnlock()
	return len(fake.pivotRootArgsForCall)
}

func (fake *FakeContainerConfigurer) PivotRootArgsForCall(i int) string {
	fake.pivotRootMutex.RLock()
	defer fake.pivotRootMutex.RUnlock()
	return fake.pivotRootArgsForCall[i].rootFSPath
}

func (fake *FakeContainerConfigurer) PivotRootReturns(result1 error) {
	fake.PivotRootStub = nil
	fake.pivotRootReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeContainerConfigurer) ChangeUser(uid int, gid int) error {
	fake.changeUserMutex.Lock()
	fake.changeUserArgsForCall = append(fake.changeUserArgsForCall, struct {
		uid int
		gid int
	}{uid, gid})
	fake.changeUserMutex.Unlock()
	if fake.ChangeUserStub != nil {
		return fake.ChangeUserStub(uid, gid)
	} else {
		return fake.changeUserReturns.result1
	}
}

func (fake *FakeContainerConfigurer) ChangeUserCallCount() int {
	fake.changeUserMutex.RLock()
	defer fake.changeUserMutex.RUnlock()
	return len(fake.changeUserArgsForCall)
}

func (fake *FakeContainerConfigurer) ChangeUserArgsForCall(i int) (int, int) {
	fake.changeUserMutex.RLock()
	defer fake.changeUserMutex.RUnlock()
	return fake.changeUserArgsForCall[i].uid, fake.changeUserArgsForCall[i].gid
}

func (fake *FakeContainerConfigurer) ChangeUserReturns(result1 error) {
	fake.ChangeUserStub = nil
	fake.changeUserReturns = struct {
		result1 error
	}{result1}
}

var _ containerizer.ContainerConfigurer = new(FakeContainerConfigurer)
